
##########################################
#     Change these variables !important
##########################################

# Set this for Copyright in the footer
owner: Pavel Kozlov

# Optional quote in the footer
# To disable set enable to false
quote:
  enable: false
  quote: Some fancy quote
  author: John Doe

# Set this to your main site title. If page doesn't have its own title,
# then this title will be used.
title: DevOps path


# Following needed for disqus integration
# Set your 'disqus' account name
#disqus: http-devopspath-ru

# Uncomment if deployed locally
url: http://localhost:4000

# Set your host if deployed not locally
# For example "https://yourGitHub.github.io"
#url: http://devopspath.ru

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
# NOTE! only change if site is NOT in master's branch
baseurl:

# Change this to your google analytics ID
google_analytics:

# Contact form pupublic key
contact_PK: 1e627c9839d6ecff44b17f30f3e0d842

##########################################
#          Optional variables
##########################################

# Set maximum posts per page
paginate: 5

# Set permalink
permalink: /:categories/:title

# MathJax support
math: false

collections:
- definitions

##########################################
#          Do not change these variables
##########################################

include:
  - _pages

sass:
  sass_dir: _sass
sass:
    style: compressed

gems:
  - jekyll-paginate
  - jekyll-sitemap # add /sitemap.xml file

paginate_path: /_pages/page:num

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
